test.cpp:33:6: note:   template argument deduction/substitution failed: test.cpp:45:14: note:   deduced conflicting types for parameter ‘T’ (‘Base’ and ‘Derive’)      show(B, D);
Template argument deduction doesn't support implicit downward-cast